# Default values for frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  branch: my-branch
  image:
    tag: master

provisioning:
  enabled: true
  prod:
    isRequired: true
    image:
      repository: trubudget/provisioning
    env:
      API_HOST: api-prod-1
      API_PORT: 8080
      ENVIRONMENT_TYPE: TEST
      ROOT_SECRET: "root-secret"
      ORGANIZATION: ACMECorp
  test:
    isRequired: true
    image:
      repository: trubudget/provisioning
    env:
      API_HOST: api-test-1
      API_PORT: 8080
      ENVIRONMENT_TYPE: TEST
      ROOT_SECRET: "root-secret"
      ORGANIZATION: ACMECorp
