# Default values for blockchain.

replicaCount: 1
global:
  image:
    tag: main
  branch: main
  exposeType: NodePort
  imageCredentials:
    name: regsecret
  env:
    PROVISIONING_TYPE: TEST
    STORAGE_TYPE: LOCAL

image:
  repository: trubudget/blockchain
  pullPolicy: Always

bc:
  isAlpha: false
  env:
    CHAINNAME: TrubudgetChain
    MULTICHAIN_RPC_PORT: 8000
    P2P_PORT: 7447
    PORT: 8085
  resources:
    memRequest: 300Mi
    memLimit: 400Mi
    cpuRequest: 350m
    cpuLimit: 400m

persistentVolume:
  name: bc-data
  storageSize: 10Gi
  volumeAccessMode: ReadWriteOnce

service:
  name: blockchain
  type: ClusterIP
  monitoring: monitoring

externalService:
  enabled: false
  type: LoadBalancer
