version: "3.2"
services:
  blockchain:
    build:
      context: ../blockchain
    environment:
      RPC_HOST: ${RPC_HOST}
      RPC_PORT: ${RPC_PORT}
      RPC_PASSWORD: ${RPC_PASSWORD}
      ORGANIZATION: ${ORGANIZATION}
    ports:
      - ${RPC_PORT}:${RPC_PORT}
      - "8085:8085"

  api:
    build:
      context: ../api
    environment:
      ORGANIZATION: ${ORGANIZATION}
      ORGANIZATION_VAULT_SECRET: ${ORGANIZATION_VAULT_SECRET}
      RPC_HOST: blockchain
      RPC_PORT: ${RPC_PORT}
      ROOT_SECRET: ${ROOT_SECRET}
      RPC_PASSWORD: ${RPC_PASSWORD}
      DOCUMENT_FEATURE_ENABLED: ${DOCUMENT_FEATURE_ENABLED}
      STORAGE_SERVICE_EXTERNAL_URL: ${STORAGE_SERVICE_EXTERNAL_URL}
      STORAGE_SERVICE_HOST: storage
      STORAGE_SERVICE_PORT: ${STORAGE_SERVICE_PORT}
      ORGANIZATION_PUBLIC_KEY: ${ORGANIZATION_PUBLIC_KEY}
      ORGANIZATION_PRIVATE_KEY: ${ORGANIZATION_PRIVATE_KEY}
      ACCESS_CONTROL_ALLOW_ORIGIN: ${ACCESS_CONTROL_ALLOW_ORIGIN}
    command: ["npm", "start"]
    # volumes:
    #   - "../api/src:/home/node/src:delegated"
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - blockchain

  provisioning:
    build:
      context: ../provisioning
    command: ["npm", "start"]
    environment:
      API_HOST: api
      API_PORT: ${API_PORT}
      ENVIRONMENT_TYPE: ${ENVIRONMENT_TYPE}
      ROOT_SECRET: ${ROOT_SECRET}
      ORGANIZATION: ${ORGANIZATION}
    depends_on:
      - api

  frontend:
    build:
      context: ../frontend
      args:
        API_HOST: api
        API_PORT: ${API_PORT}
    depends_on:
      - api
    ports:
      - "3000:3000"

  storage:
    build:
      context: .
    environment:
      STORAGE_SERVICE_PORT: ${STORAGE_SERVICE_PORT}
      ACCESS_CONTROL_ALLOW_ORIGIN: ${ACCESS_CONTROL_ALLOW_ORIGIN}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_HOST: minio
      MINIO_PORT: ${MINIO_PORT}
    depends_on:
      - api
    command: ["npm", "start"]
    # volumes:
    #   - "../storage-service/src:/home/node/src:delegated"
    ports:
      - "${STORAGE_SERVICE_PORT}:${STORAGE_SERVICE_PORT}"

  minio:
    image: minio/minio:RELEASE.2021-06-17T00-10-46Z
    ports:
      - ${MINIO_PORT}:${MINIO_PORT}
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
