version: "3.2"
services:
  api:
    image: trubudget/api:${TAG}
    environment:
      RPC_HOST: master
      RPC_PORT: ${RPC_PORT}
      RPC_PASSWORD: ${RPC_PASSWORD}
      PORT: ${API_PORT}
      ORGANIZATION: ${ORGANIZATION}
      ROOT_SECRET: ${ROOT_SECRET}
      ORGANIZATION_VAULT_SECRET: ${ORGANIZATION_VAULT_SECRET}
      SWAGGER_BASEPATH: /test
    ports:
      - "8080:8080" # Mapping the nginx port
    links:
      - master

  master:
    image: trubudget/blockchain:${TAG}
    environment:
      RPC_PORT: ${RPC_PORT}
      RPC_PASSWORD: ${RPC_PASSWORD}
      ORGANIZATION: ${ORGANIZATION}

  frontend:
    image: trubudget/frontend:${TAG}
    ports:
      - "80:80" # Mapping the nginx port
    environment:
      PROD_API_HOST: api
      PROD_API_PORT: ${API_PORT}
      TEST_API_HOST: api
      TEST_API_PORT: ${API_PORT}
    links:
      - api

  provisioning:
    image: trubudget/provisioning:${TAG}
    command: ["npm", "start"]
    environment:
      API_HOST: api
      API_PORT: 8080
      ENVIRONMENT_TYPE: TEST
      ROOT_SECRET: ${ROOT_SECRET}
      ORGANIZATION: ${ORGANIZATION}

  e2etest:
    build:
      context: "../../e2e-test"
    links:
      - frontend
    depends_on:
      - frontend
      - master
      - api
