version: "3.2"
services:
  master-node:
    build:
      context: ../blockchain
    environment:
      RPC_PORT: 8000
      RPC_PASSWORD: s750SiJnj50yIrmwxPnEdSzpfGlTAHzhaUwgqKeb0G1j
      ORGANIZATION: KfW
      EMAIL_SERVICE: "ENABLED"
      EMAIL_HOST: email-service
      EMAIL_PORT: 8890
      JWT_SECRET: uYbE6y1nrRkhN2EvderoxNpTS2JkaZbk
      LOG_LEVEL: INFO
    links:
      - email-service
    ports:
      - "8000:8000"
      - "8085:8085"
  email-service:
    build: .
    command: ["npm", "start"]
    environment:
      JWT_SECRET: uYbE6y1nrRkhN2EvderoxNpTS2JkaZbk
      SMTP_HOST: host.docker.internal
      SMTP_PORT: 2500
      DB_HOST: emaildb
      DB_PORT: 5432
      DB_NAME: trubudget_email_service
      PORT: 8890
      LOG_LEVEL: INFO
      # MODE: DEBUG
    links:
      - emaildb
    ports:
      - "8890:8890"
  emaildb:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST: localhost
      POSTGRES_PASSWORD: test
      POSTGRES_PORT: 5432
      POSTGRES_DB: trubudget_email_service
    ports:
      - 5432:5432
  master-api:
    image: trubudget/api:latest
    environment:
      ORGANIZATION: KfW
      ORGANIZATION_VAULT_SECRET: asdf
      RPC_HOST: master-node
      RPC_PORT: 8000
      ROOT_SECRET: asdf
      RPC_PASSWORD: s750SiJnj50yIrmwxPnEdSzpfGlTAHzhaUwgqKeb0G1j
      JWT_SECRET: uYbE6y1nrRkhN2EvderoxNpTS2JkaZbk
    ports:
      - 8080:8080
    links:
      - master-node
  provisioning:
    image: trubudget/provisioning:latest
    command: ["npm", "start"]
    environment:
      API_HOST: master-api
      API_PORT: 8080
      ENVIRONMENT_TYPE: TEST
      ROOT_SECRET: asdf
      ORGANIZATION: KfW
    links:
      - master-api
  # frontend:
  #   build: ../frontend
  #   environment:
  #     PROD_API_HOST: master-api
  #     PROD_API_PORT: 8080
  #     TEST_API_HOST: master-api
  #     TEST_API_PORT: 8080
  #   ports:
  #     - "81:80" # Mapping the nginx port
  #   links:
  #     - master-api
