version: "3.7"
services:
  blockchain:
    platform: linux/amd64
    build: .
    environment:
      PORT: 8085
      MULTICHAIN_RPC_PORT: ${MULTICHAIN_RPC_PORT}
      MULTICHAIN_RPC_PASSWORD: ${MULTICHAIN_RPC_PASSWORD}
      ORGANIZATION: ${ORGANIZATION}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_SERVICE_ENABLED: ${EMAIL_SERVICE_ENABLED}
      LOG_LEVEL: ${BLOCKCHAIN_LOG_LEVEL}
      PRETTY_PRINT: ${PRETTY_PRINT}
      NODE_ENV: ${NODE_ENV}
      CERT_PATH: ${CERT_PATH}
      CERT_CA_PATH: ${CERT_CA_PATH}
      CERT_KEY_PATH: ${CERT_KEY_PATH}
    ports:
      - ${MULTICHAIN_RPC_PORT}:${MULTICHAIN_RPC_PORT} # port for connecting API
      - "8085:8085" # port for backup
      - "7447:7447" # port for connecting beta (P2P)


