services:
  frontend:
    image: trubudget/frontend:${TAG}
    environment:
      NODE_ENV: ${ENVIRONMENT}
      REACT_APP_VERSION: ${REACT_APP_VERSION}
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
      INLINE_RUNTIME_CHUNK: ${INLINE_RUNTIME_CHUNK}
      REACT_APP_LOGGING: ${REACT_APP_LOGGING}
      REACT_APP_LOG_LEVEL: ${FRONTEND_LOG_LEVEL}
      REACT_APP_LOGGING_SERVICE_HOST: ${REACT_APP_LOGGING_SERVICE_HOST}
      REACT_APP_LOGGING_SERVICE_PORT: ${REACT_APP_LOGGING_SERVICE_PORT}
      REACT_APP_LOGGING_SERVICE_HOST_SSL: ${REACT_APP_LOGGING_SERVICE_HOST_SSL}
      REACT_APP_LOGGING_PUSH_INTERVAL: ${REACT_APP_LOGGING_PUSH_INTERVAL}
    # networks:
    #   mynetwork:
    #     ipv4_address: 172.20.0.91
    ports:
      - "${FRONTEND_PORT}:80"
    # depends_on:
    #   - api
