# Default values for trubudget-excel-export.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: trubudget/excel-export
  pullPolicy: Always

excelExport:
  env:
    PROD_API_HOST: api
    PROD_API_PORT: 8080
    TEST_API_HOST: testapi
    TEST_API_PORT: 8080
    PORT: 8888
  # resources:
  #   memRequest: 150Mi
  #   memLimit: 200Mi
  #   cpuRequest: 100m
  #   cpuLimit: 150m
  probes:
    enabled: true

service:
  name: excel-export
  type: ClusterIP
  monitoring: monitoring
